name: Build and deploy
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build

      # This step prints an output (time) from the previous step's action.
      - name: Deploy
        # uses: action/heroku 
        run: heroku help 